language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
before_install:
  - npm install -g firebase-tools
  - npm install
script:
  - npm test
  - npm run build
after_success:
  - firebase use default --token $FIREBASE_TOKEN
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master
