language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
  - npm -g config set user root
  - npm install -g firebase-tools
  - npm install
script:
  - npm test
after_success:
  - npm run build
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master
